SETTING_FILENAME = 'filename'
SETTING_RECENT_FILES = 'recentFiles'
SETTING_WIN_SIZE = 'window/size'
SETTING_WIN_POSE = 'window/position'
SETTING_WIN_GEOMETRY = 'window/geometry'
SETTING_LINE_COLOR = 'line/color'
SETTING_FILL_COLOR = 'fill/color'
SETTING_ADVANCE_MODE = 'advanced'
SETTING_WIN_STATE = 'window/state'
SETTING_SAVE_DIR = 'savedir'
SETTING_PAINT_LABEL = 'paintlabel'
SETTING_LAST_OPEN_DIR = 'lastOpenDir'
SETTING_AUTO_SAVE = 'autosave'
SETTING_SINGLE_CLASS = 'singleclass'
FORMAT_PASCALVOC='PascalVOC'
FORMAT_YOLO='YOLO'
FORMAT_CREATEML='CreateML'
SETTING_DRAW_SQUARE = 'draw/square'
SETTING_LABEL_FILE_FORMAT= 'labelFileFormat'
SETTING_LAST_OPENED_DIR = 'lastOpenedDir'
SETTING_YOLO_EXPORT_DIR = 'yoloExportDir'
SETTING_MODEL_EXPORT_DIR = 'modelExportDir'
DEFAULT_ENCODING = 'utf-8'

# 新增：启动行为与目录统计配置
# 是否在启动时自动加载上次打开的目录（默认 False，避免大目录导致启动卡顿）
SETTING_AUTO_LOAD_LAST_DIR = 'autoLoadLastDir'
# 上次目录的图片数量统计（用于后续优化与提示，非必需）
SETTING_LAST_DIR_IMAGE_COUNT = 'lastDirImageCount'
